[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = "0.56.0"
exhaust = "0.2.4"
grid = "1.0.0"
itertools = "0.14.0"
pathfinding = "4.14.0"
peg = "0.8.5"
petgraph = "0.8.3"
rayon = "1.11.0"
regex = "1.12.2"
rustc-hash = "2.1.1"
util = { path = "../util" }
